[model]
max_context_len = 336
max_pred_len = 168
e_layers = 18
n_heads = 12
d_model = 768
d_ff = 2048
dropout = 0.0
fc_dropout = 0.0
head_dropout = 0.0
patch_len = 12
stride = 8
revin = true
affine = true
subtract_last = false
continuous_loads = true
continuous_head = 'huber'

[pretrain]
batch_size = 32
init_scale = 0.02
warmup_steps = 10000
lr = 0.00006
train_tokens = 2000000000
eval_every = 200
apply_scaler_transform = 'boxcox'
note = ''

[zero_shot]
apply_scaler_transform = 'boxcox'

[transfer_learning]
apply_scaler_transform = 'boxcox'
