[model]
context_len = 168
pred_len = 24
max_context_len = 336
max_pred_len = 168
num_encoder_layers = 6
num_decoder_layers = 8
nhead = 12
dim_feedforward = 2048
d_model = 768
dropout = 0.0
activation = 'gelu'
continuous_loads = true
ignore_spatial = false
continuous_head = 'huber'
num_experts = 8
top_k = 2
# aux_loss_weight = 0.01

[pretrain]
batch_size = 32
init_scale = 0.02
warmup_steps = 20000
lr = 0.00006
train_tokens = 4000000000
apply_scaler_transform = 'boxcox'
note = "Update-19-huber"

[zero_shot]
batch_size = 2048
apply_scaler_transform = 'boxcox'

[transfer_learning]
apply_scaler_transform = 'boxcox'
