[model]
context_len = 168
pred_len = 24
max_context_len = 336
max_pred_len = 168
num_encoder_layers = 2
num_decoder_layers = 2
nhead = 4
dim_feedforward = 512
d_model = 256
dropout = 0.0
# activation = 'gelu'
continuous_loads = true
ignore_spatial = false
continuous_head = 'huber'
num_experts = 4
top_k = 2
# aux_loss_weight = 0.01
# num_groups = 2
# experts_per_gp = 2

[pretrain]
batch_size = 256
init_scale = 0.02
warmup_steps = 10000
lr = 0.00006
train_tokens = 8000000000
apply_scaler_transform = 'boxcox'
note = "Update-20-huber"

[zero_shot]
apply_scaler_transform = 'boxcox'

[transfer_learning]
apply_scaler_transform = 'boxcox'
